version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: kolaincDB
      MYSQL_USER: kolaincUser
      MYSQL_PASSWORD: alokcni
      MYSQL_ROOT_PASSWORD: alokcni
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: django_app
    command: gunicorn KOLA_INC.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: kolaincDB
      DB_USER: kolaincUser
      DB_PASSWORD: alokcni
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:
