# Generated by Django 5.2.4 on 2025-09-17 21:43

import Kola_app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchardId', models.CharField(max_length=191, unique=True)),
                ('checkoutId', models.CharField(max_length=191, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('isSuccessful', models.BooleanField(default=False)),
                ('ResultDesc', models.CharField(max_length=191, null=True)),
                ('MpesaReceiptNumber', models.CharField(max_length=191, null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate')], max_length=20)),
                ('scanned_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=191, validators=[Kola_app.models.validate_email_domain])),
                ('phone', models.CharField(max_length=20, validators=[Kola_app.models.validate_kenyan_phone_number])),
                ('ticket_type', models.CharField(choices=[('earlyBird', 'Early Bird'), ('standard', 'Standard'), ('gate', 'Gate')], max_length=50)),
                ('ticket_price', models.IntegerField()),
                ('number_of_tickets', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit Card'), ('cash', 'Cash')], default='mpesa', max_length=20)),
                ('mpesa_number', models.CharField(blank=True, max_length=20, validators=[Kola_app.models.validate_kenyan_phone_number])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('unique_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unique_code'], name='Kola_app_ti_unique__ae709b_idx'), models.Index(fields=['is_used'], name='Kola_app_ti_is_used_d47af0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('duplicate', 'Duplicate Scan')], max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='Kola_app.ticket')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['scanned_at'], name='Kola_app_ti_scanned_dd0099_idx'), models.Index(fields=['status'], name='Kola_app_ti_status_07c494_idx')],
            },
        ),
    ]
