# Generated by Django 5.2.4 on 2025-09-18 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='Kola_app.ticket'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['slug'], name='Kola_app_ev_slug_64d780_idx'), models.Index(fields=['is_active'], name='Kola_app_ev_is_acti_e45924_idx'), models.Index(fields=['date'], name='Kola_app_ev_date_29dc5a_idx')],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Kola_app.event'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event'], name='Kola_app_ti_event_i_795424_idx'),
        ),
    ]
