# Generated by Django 5.2.4 on 2025-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0002_contactsubmission_ticket_payment_ticket_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
