# Generated by Django 5.2.4 on 2025-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0002_ticket_unique_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='ticketscan',
            name='scanned_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketscan',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketscan',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=20),
        ),
    ]
