# Generated by Django 5.2.4 on 2025-09-27 13:27

import Kola_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0003_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_number', models.CharField(choices=[('Event 1', 'Event 1'), ('Event 2', 'Event 2'), ('Event 3', 'Event 3'), ('Event 4', 'Event 4'), ('Event 5', 'Event 5')], max_length=10)),
                ('event_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('event_poster', models.ImageField(upload_to='events/posters/', validators=[Kola_app.models.validate_event_poster_dimensions])),
                ('event_location', models.CharField(max_length=200)),
                ('event_host', models.CharField(default='By Kola', max_length=100)),
                ('event_date', models.DateField(help_text='Actual date of the event')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher number appears first (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Schedule',
                'verbose_name_plural': 'Event Schedules',
                'ordering': ['-display_order', '-event_date'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
