# Generated by Django 5.2.4 on 2025-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0004_eventschedule_remove_ticket_event_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='catalogue_link',
            field=models.CharField(blank=True, help_text='Optional: Custom URL for this event in catalogue', max_length=200),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='catalogue_order',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first in catalogue'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='show_in_catalogue',
            field=models.BooleanField(default=False, help_text='Show this event in the catalogue carousel'),
        ),
    ]
