# Generated by Django 5.2.4 on 2025-09-10 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0005_alter_ticket_ticket_type_remove_ticket_is_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.DeleteModel(
            name='TicketBooking',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('earlyBird', 'Early Bird'), ('standard', 'Standard'), ('gate', 'Gate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
