# Generated by Django 5.2.4 on 2025-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0006_remove_ticket_event_delete_ticketbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchardId', models.CharField(max_length=100, unique=True)),
                ('checkoutId', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('ResultCode', models.IntegerField(max_length=20, null=True)),
                ('ResultDesc', models.CharField(max_length=100, null=True)),
                ('CustomerMessage', models.CharField(max_length=100, null=True)),
                ('MpesaReceiptNumber', models.CharField(max_length=100, null=True, unique=True)),
                ('amount', models.IntegerField(max_length=100000, null=True)),
                ('Balance', models.CharField(max_length=100, null=True)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
