# Generated by Django 5.2.4 on 2025-09-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0007_mpesaresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaResponse',
            new_name='Payment',
        ),
    ]
