# Generated by Django 5.2.4 on 2025-09-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0008_rename_mpesaresponse_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='CustomerMessage',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ResultCode',
        ),
        migrations.AddField(
            model_name='payment',
            name='isSuccessful',
            field=models.BooleanField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
