# Generated by Django 5.2.4 on 2025-09-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0009_remove_payment_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
