# Generated by Django 5.2.4 on 2025-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0010_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='MpesaReceiptNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ResultDesc',
            field=models.CharField(max_length=100),
        ),
    ]
