# Generated by Django 5.2.4 on 2025-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kola_app', '0011_alter_payment_mpesareceiptnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='MpesaReceiptNumber',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ResultDesc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
